scalacenter/scastie

api/src/main/scala/api/Api.scala, api/src/main/scala/api/Runtime.scala, client/src/main/assets/_app.less, client/src/main/assets/_codemirror.less, client/src/main/assets/_codemirror_solarized.less, client/src/main/scala/client/App.scala, client/src/main/scala/client/CodemirrorEditor.scala, client/src/main/scala/client/ScaladexSearch.scala, client/src/main/scala/client/Settings.scala, client/src/main/scala/client/Views.scala, demo/dotty.scala, demo/scrimage.scala, sbt-runner/src/main/scala/com.olegych.scastie.sbt/SbtActor.scala, scastie/app/com.olegych.scastie.web/PasteActor.scala, scastie/app/controllers/Application.scala
* update demo code
* misc ui fixes
=> save ressource

api/src/main/scala/api/Api.scala, build.sbt, client/src/main/assets/_codemirror.less, client/src/main/assets/_codemirror_solarized.less, client/src/main/scala/client/App.scala, client/src/main/scala/client/Editor.scala, client/src/main/scala/client/Model.scala, demo/scrimage.scala, deployment/sbt.sh, sbt-api/src/main/scala/sbtapi/SbtApi.scala, sbt-runner/src/main/resources/application.conf, sbt-runner/src/main/scala/com.olegych.scastie.sbt/Sbt.scala, sbt-runner/src/main/scala/com.olegych.scastie.sbt/SbtActor.scala, sbt-runner/src/test/scala/SbtActorTest.scala, sbt-scastie/src/main/scala/com.olegych.scastie.sbtscastie/CompilerReporter.scala, sbt-scastie/src/main/scala/com.olegych.scastie.sbtscastie/RuntimeErrorLogger.scala, sbt-scastie/src/main/scala/com.olegych.scastie.sbtscastie/SbtScastiePlugin.scala, scastie/conf/actors.conf
* split output into sbt messages and user println
* offset the runtime error position when instrumenting
* exit sbt in tests
=> custom sbt logger to intercept runtime error and user messages

api/src/main/scala/com.olegych.scastie.api/Runtime.scala
Issue: #77
Provide hint to close help page by removing help expression
=> Provide hint to close help page #77

client/src/main/assets/public/css/dark-style.css, client/src/main/assets/public/css/light-style.css, client/src/main/scala/com.olegych.scastie.client/Help.scala, server/src/main/resources/public/views/index.html
This PR contains changes related to fix the following issues in the Scastie's UI:
- Fonts not loading correctly.
- Modified colors for Editor's **Console** in the **Light** theme. 
@heathermiller @MasseGuillaume could you please review it?
Thanks!
=> Scastie UI fix issues fonts and styles

client/src/main/scala/com.olegych.scastie.client/App.scala, client/src/main/scala/com.olegych.scastie.client/AppBackend.scala, client/src/main/scala/com.olegych.scastie.client/Editor.scala
Hi. `App.scala` was linked from Reddit and after having a brief look I saw a few places where minor refactoring is possible. I didn't do a everything possible nor look at the whole project but for `App` and `AppBackend` there are two commits that make minor improvements.
=> Minor scalajs-react refactoring

project/Deployment.scala
on scastie.scala-lang.org
server.sh restart the server
on scastie-sbt.scala-lang.org
sbt.sh restart the sbt instances
=> fix #151 restart servers with upstart

balancer/src/main/scala/com.olegych.scastie.balancer/DispatchActor.scala, balancer/src/main/scala/com.olegych.scastie.balancer/StatusActor.scala, client/src/main/scala/com.olegych.scastie.client/ScastieBackend.scala, client/src/main/scala/com.olegych.scastie.client/components/MainPanel.scala, client/src/main/scala/com.olegych.scastie.client/components/Scastie.scala, client/src/main/scala/com.olegych.scastie.client/components/Status.scala, server/src/main/scala/com.olegych.scastie.web/ServerMain.scala
=> fetch status update from backend on connect to status actor

build.sbt, client/src/main/assets/public/sass/codemirror.scss, client/src/main/scala/com.olegych.scastie.client/AnsiColorFormatter.scala, client/src/main/scala/com.olegych.scastie.client/components/Editor.scala
=> implement formatting for ANSI colors in error output for editor window

project/plugins.sbt
it fixes this issue:
https://github.com/marcuslonnberg/sbt-docker/issues/63
=> update sbt-docker to 1.4.1

README.MD, api/src/main/scala/com.olegych.scastie.api/ApiModels.scala, client/src/main/scala/com.olegych.scastie.client/ScastieBackend.scala, client/src/main/scala/com.olegych.scastie.client/components/Scastie.scala, sbt-runner/src/main/scala/com.olegych.scastie.sbt/SbtMain.scala, sbt-runner/src/main/scala/com.olegych.scastie.sbt/SbtRunner.scala, server/src/main/scala/com.olegych.scastie.web/routes/AssetsRoutes.scala, server/src/main/scala/com.olegych.scastie.web/routes/AutowireApiRoutes.scala, server/src/main/scala/com.olegych.scastie.web/routes/DebugRoutes.scala, server/src/main/scala/com.olegych.scastie.web/routes/DownloadRoutes.scala, server/src/main/scala/com.olegych.scastie.web/routes/FrontPageRoutes.scala, server/src/main/scala/com.olegych.scastie.web/routes/OAuth2Routes.scala, server/src/main/scala/com.olegych.scastie.web/routes/ProgressRoutes.scala, server/src/main/scala/com.olegych.scastie.web/routes/PublicRoutes.scala, server/src/main/scala/com.olegych.scastie.web/routes/ScalaJsRoutes.scala, server/src/main/scala/com.olegych.scastie.web/routes/StatusRoutes.scala
post code to /scala-lang and get a snippet url back
this is temporary until we have a proper embeded mode
=> Add api endpoint for scala-lang.org website

instrumentation/src/main/scala/com.olegych.scastie.instrumentation/Instument.scala, sbt-runner/src/test/scala/com.olegych.scastie.sbt/SbtActorTest.scala
=> Update calls to locally and println to use fully qualified paths.

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala, sbt-shared/SbtShared.scala
=> Release Dotty 0.5.0-RC1

client/src/main/scala/com.olegych.scastie.client/ClientMain.scala, client/src/main/scala/com.olegych.scastie.client/Routing.scala, client/src/main/scala/com.olegych.scastie.client/RoutingADT.scala, client/src/main/scala/com.olegych.scastie.client/components/ScaladexSearch.scala, client/src/main/scala/com.olegych.scastie.client/components/Scastie.scala, client/webpack/webpack-dev.config.js
Add a url sheme to redirect from scaladex to scastie, selecting a library and a scala target: 
ex: 
https://scastie.scala-lang.org/try?g=com.chuusai&a=shapeless&v=2.3.3&t=JVM&sv=2.12.6
https://github.com/scalacenter/scaladex/issues/540
=> Try a library

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala
Reference https://github.com/lampepfl/dotty.g8/tree/master/src/main/g8
=> Update sbt-dotty to 0.3.4

build.sbt, client/src/main/scala/com.olegych.scastie.client/components/editor/CodeReadOnly.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/EditorBackend.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/EditorState.scala, client/yarn.lock
Added comments which allows to make part of code readonly.
Marking:
- `// read-only` - start of readonly code
- `// end-read-only` - end of readonly code
After marking part of code, comments are immutable, so mark cannot be removed. 
If you have ideas how to improve this code/functionality let me know :slightly_smiling_face:
=> Marking part of code as ready only

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala, build.sbt, client/src/main/resources/embed.html, client/src/main/scala/com.olegych.scastie.client/EmbeddedOptions.scala, project/SbtShared.scala, project/plugins.sbt, project/project/plugins.sbt, runtime-scala/src/main/scalajvm-2/com.olegych.scastie.api.runtime/Runtime.scala, runtime-scala/src/main/scalajvm-3/com.olegych.scastie.api.runtime/Runtime.scala, runtime-scala/src/main/scalajvm/com.olegych.scastie.api.runtime/Runtime.scala, sbt-runner/src/main/scala/com.olegych.scastie.sbt/FormatActor.scala
Support worksheetMode in scala3
See also commit messages
=> Scala3 worksheet

api/src/main/scala/com.olegych.scastie.api/Inputs.scala, sbt-runner/src/test/scala/com.olegych.scastie.sbt/SbtActorTest.scala
That way the default will always be the latest released version of
Scala.
=> Make Scala 3 the default target

sbt-runner/src/main/scala/com.olegych.scastie.sbt/FormatActor.scala
Closes #511 
Both SbtRunner and the dialect must be set in order to process scala3 worksheets.
=> Support formatting of Scala3 worksheet

build.sbt, sbt-runner/src/main/scala/com.olegych.scastie.sbt/FormatActor.scala, sbt-runner/src/test/scala/com.olegych.scastie.sbt/FormatActorTest.scala
Following up on https://github.com/scalacenter/scastie/pull/515#issuecomment-901122404 I am opening this PR to investigate the problem. First step, I added some simple tests.
=> Test and Fix worksheet formatting

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala, api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala, client/src/main/scala/com.olegych.scastie.client/components/BuildSettings.scala, project/SbtShared.scala, project/project/plugins.sbt
Before 
After
I am unable to test this locally because `stbRunner/test` hands indefinitely
=> Choose ScalaVersion for ScalaJS snippets

api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala, project/SbtShared.scala
=> Add support for Scala 2.13.7

build.sbt, storage/src/main/scala/com.olegych.scastie.storage/SnippetsContainer.scala
=> Update zip4j to 2.9.1

build.sbt, client/src/main/scala/com.olegych.scastie.client/ScastieBackend.scala, client/src/main/scala/com.olegych.scastie.client/components/CopyModal.scala, client/src/main/scala/com.olegych.scastie.client/components/ScaladexSearch.scala, client/src/main/scala/com.olegych.scastie.client/components/Scastie.scala, project/SbtShared.scala
I got it to compile, but was unable to test locally, because of node-sass...
Can anybody with a working setup please test?
=> Update scalas-react to 2.1.1, scalajs-dom to 2.2.0

build.sbt, sbt-runner/src/main/scala/com.olegych.scastie.sbt/FormatActor.scala
this came up over at https://github.com/scala/community-build/pull/1591
=> Scalafmt 3.5.8 (was 3.0.4)

build.sbt, storage/src/main/scala/com.olegych.scastie.storage/MongoDBSnippetsContainer.scala
This will likely fix CI as we will be using latest MongoDB driver supporting MongoDB v6
=> Replace reactive-mongo with official mongodb driver

storage/src/main/scala/com.olegych.scastie.storage/MongoDBSnippetsContainer.scala, storage/src/test/scala/com.olegych.scastie.storage/SnippetsContainerTest.scala
Previously I left one place without explicit parse to Bson which lead to log spam in Scastie. This should fix this issue
=> properly parse SnippetProgress to Bson

build.sbt, client/src/main/resources/dev/main.js, client/src/main/resources/prod/main.js, project/SbtShared.scala
Current main can't run scalajs, as it was recently bumped to newest version and I only added dependency for client, not all scalajs projects.
=> properly add scalajs-java-securerandom to all scalajs dependencies

api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala, project/SbtShared.scala
Copied from: https://github.com/scalacenter/scastie/commit/7529a199626f8a9e05d2a8570a3313643b63315e
=> add Scala 2.13.10

CONTRIBUTING.md, build.sbt, deployment/deploy.sh, metals-runner/src/main/scala/scastie/metals/ScastieMetalsRoutes.scala, project/Deployment.scala, server/src/main/scala/com.olegych.scastie.web/ServerMain.scala
deployStaging and deployProd no longer automatically pushes the docker images.
It will prevent pushing them more than 1 time in case deployment scripts fail.
=> Improve and fix deployment

client/src/main/resources/sass/tooltip.scss, client/src/main/scala/com.olegych.scastie.client/components/Scastie.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/InteractiveProvider.scala, metals-runner/src/main/scala/scastie/metals/DTOExtensions.scala
=> Fix noncompiling snippets on safari when using scala.js

build.sbt, package.json, project/Deployment.scala, project/SbtShared.scala, vite.config.js, yarn.lock
Merge after #692 as this is dependent on that branch.
fixes https://github.com/scalacenter/scastie/issues/688
=> Bump scala js vite

build.sbt, client/src/main/scala/com.olegych.scastie.client/components/editor/CodeEditor.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/SimpleEditor.scala, project/SbtShared.scala, project/plugins.sbt, sbt-runner/src/main/scala/com.olegych.scastie.sbt/FormatActor.scala
I'll separate bumping of Scala version to separate PR.
Also we can't bump ScalablyTyped and SBT because of breaking changes upstream:
https://github.com/ScalablyTyped/Converter/issues/505
They will be merged after fix in one / two weeks at: #696
=> Bump libraries

client/src/main/scala/com.olegych.scastie.client/components/editor/InteractiveProvider.scala
fixes https://github.com/scalacenter/scastie/issues/709
=> Properly set tooltip range so we can select it

client/src/main/scala/com.olegych.scastie.client/components/editor/CodeEditor.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/SimpleEditor.scala, project/build.properties, project/plugins.sbt
Also bumps sbt native packager.
Merge after new version of ScalablyTyped is released with fix.
=> Bump SBT and ScalablyTyped and sbt native packager

server/src/main/scala/com.olegych.scastie.web/ServerMain.scala
Fixes the routes so they are not created again on every new api call.
=> Fix akka http server routes

client/src/main/resources/sass/dark.scss, client/src/main/scala/com.olegych.scastie.client/components/editor/CodeEditor.scala
This should partially fix https://github.com/scalacenter/scastie/issues/198#issuecomment-1385215157
=> fix active-line selection and add proper background for inputs settings

client/src/main/scala/com.olegych.scastie.client/components/VersionSelector.scala, project/SbtShared.scala
Removes radio button version selector as it is misleading
=> Add latest RC, fix version selector

metals-runner/src/main/scala/scastie/metals/PresentationCompilers.scala
Fixes https://github.com/scalacenter/scastie/issues/721
=> Add java sources

client/src/main/resources/sass/editor.scss
Fixes https://github.com/scalacenter/scastie/issues/841
=> remove font ligatures from editor

build.sbt
This is only temporal adjustment. In the future it will be hidden behind configuration.
=> Increase scastie-metals-runner Xmx to 12g

instrumentation/src/main/scala/com.olegych.scastie.instrumentation/Instrument.scala, instrumentation/src/main/scala/com.olegych.scastie.instrumentation/InstrumentedInputs.scala, sbt-runner/src/main/scala/com.olegych.scastie.sbt/SbtProcess.scala
Fixes https://github.com/scalacenter/scastie/issues/651
=> Worksheet snippets should compile, even when there is parsing error

client/src/main/scala/com.olegych.scastie.client/components/editor/CodeEditor.scala, sbt-runner/src/main/scala/com.olegych.scastie.sbt/OutputExtractor.scala
Fixes https://github.com/scalacenter/scastie/issues/749
=> ensure all diagnostics start with 1

api/src/main/scala/com.olegych.scastie.api/ApiModels.scala, client/src/main/scala/com.olegych.scastie.client/components/EmbeddedOverlay.scala, client/src/main/scala/com.olegych.scastie.client/components/LoginModal.scala, client/src/main/scala/com.olegych.scastie.client/components/NewButton.scala, client/src/main/scala/com.olegych.scastie.client/components/PrivacyPolicyModal.scala, client/src/main/scala/com.olegych.scastie.client/components/PrivacyPolicyPrompt.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/DebouncingCapabilities.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/EditorTextOps.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/InteractiveProvider.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/MetalsAutocompletion.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/MetalsClient.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/MetalsHover.scala, metals-runner/src/main/scala/scastie/metals/DTOExtensions.scala, metals-runner/src/main/scala/scastie/metals/JavaConverters.scala, metals-runner/src/main/scala/scastie/metals/ScastieMetalsRoutes.scala, metals-runner/src/test/scala/scastie/metals/TestUtils.scala, package.json, storage/src/main/scala/com.olegych.scastie.storage/inmemory/InMemorySnippetsContainer.scala, yarn.lock
Fixes https://github.com/scalacenter/scastie/issues/722
Fixes https://github.com/scalacenter/scastie/issues/710
The second issue need upstream fix on metals:
https://github.com/scalameta/metals/issues/5361
=> Fix multiple issues with autocompletions

client/src/main/scala/com.olegych.scastie.client/components/TopBar.scala
Fixes https://github.com/scalacenter/scastie/issues/889
=> update github issues link

.github/workflows/test.yml, balancer/src/test/scala/com.olegych.scastie.balancer/LoadBalancerRecoveryTest.scala, metals-runner/src/test/scala/scastie/metals/MetalsDispatcherTest.scala
Quick changes to not fail CI if stress tests fail
=> Make test timeout longer, add flaky to metals test

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala, metals-runner/src/main/scala/scastie/metals/MetalsDispatcher.scala
Fixes: https://github.com/scalacenter/scastie/issues/728
=> fix: properly check if dependency is supported

client/src/main/scala/com.olegych.scastie.client/components/editor/DebouncingCapabilities.scala, client/src/main/scala/com.olegych.scastie.client/components/editor/EditorKeymaps.scala
Fixes: https://github.com/scalacenter/scastie/issues/719
=> Add tab autocompletion + adjust the completion debounce

instrumentation/src/main/scala/com.olegych.scastie.instrumentation/Instrument.scala
Fixes https://github.com/scalacenter/scastie/issues/778
Fixes https://github.com/scalacenter/scastie/issues/625
=> Support source-future

instrumentation/src/main/scala/com.olegych.scastie.instrumentation/Instrument.scala, sbt-runner/src/test/scala/com.olegych.scastie.sbt/SbtActorTest.scala
Fixes https://github.com/scalacenter/scastie/issues/918
=> fix last line comment

client/src/main/scala/com.olegych.scastie.client/components/editor/MetalsAutocompletion.scala, metals-runner/src/main/scala/scastie/metals/ScastieSymbolSearch.scala
Fixes https://github.com/scalacenter/scastie/issues/940
=> Fix dot autocompletion

client/src/main/resources/sass/tooltip.scss
Fixes https://github.com/scalacenter/scastie/issues/927
=> Fix non scrollable tooltips

client/src/main/scala/com.olegych.scastie.client/components/Scastie.scala
Fixes https://github.com/scalacenter/scastie/issues/741
=> Snippet loading fix

api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala, project/SbtShared.scala, project/build.properties
=> add Scala 2.13.13 and 2.12.19

api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala, project/SbtShared.scala
=> Update Scala 2 and Scala 3 versions
