docker/Dockerfile

Due to some standard fonts missing in the SBT runner image, the JVM was failing to load the fonts when running any font-related code. DejaVu fonts are added to mitigate this, as per https://github.com/docker-library/openjdk/issues/73#issuecomment-207816707.
Additionally, the Source Code Pro fonts are added. They look somewhat better and are used by [reftree](https://github.com/stanch/reftree).
See also: #165.

Improve font configuration in SBT runner docker images

---

client/src/main/scala/com.olegych.scastie.client/ApiReusability.scala
client/src/main/scala/com.olegych.scastie.client/AppBackend.scala
client/src/main/scala/com.olegych.scastie.client/Views.scala
client/src/main/scala/com.olegych.scastie.client/components/MainPanel.scala
client/src/main/scala/com.olegych.scastie.client/components/TopBar.scala

Hi! Here you go, I hope this is helpful. If you're new to `Reusability` see [doc here](https://github.com/japgolly/scalajs-react/blob/master/doc/PERFORMANCE.md) for an explanation. Cheers!
---
In regards to scalajs-react usage, I forsee two styles of use becoming
problematic in future and would like to take this opportunity to
demonstrate an appealing alternative. The problems:
1. React's shouldComponentRender hooks are used to determine whether a
component tree need be rerendered, analysed and compared with previous
vdom. Scastie currently does not make use of this feature and so when
any change occurs anywhere on the screen, the entire page is
re-calculated.
2. Unit tests currently don't exist but are in the backlog. Most
components currently ask for much more data that they require, …

Prevent wasted recalculations of TopBar

---

sbt-runner/src/main/scala/com.olegych.scastie.sbt/Sbt.scala
sbt-runner/src/test/scala/com/olegych/scastie/sbt/EnsimeActorTests.scala
sbt-runner/src/test/scala/com/olegych/scastie/sbt/SbtActorTest.scala

* There is no distinction between stderr to stdout but it's a simple solution. Otherwise we need to start two threads the two streams
* Increase the test timeout to see if it fix travis ci

Redirect stderr to stdout (fix #284)

---

project/plugins.sbt

I found out sbt-scalajs-bundler 0.9.0-SNAPSHOT is no longer existed. The real version number [already released](https://github.com/scalacenter/scalajs-bundler/blob/master/manual/src/ornate/changelog.md#version-090). So I updated to real version.

Bump sbt-scalajs-bundler to real version.

---

build.sbt

Run `bin/scalafmt --test` will throw the execption.
```scala
Exception in thread "main" org.scalafmt.Error$MisformattedFile: /home/travis/build/scalacenter/scastie/build.sbt is mis-formatted. 
```

Fix build.sbt is mis-formatted issue.

---

api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala

Original comment - https://github.com/scalacenter/scastie/pull/369#issuecomment-349693246
Github Release Note - https://github.com/scala/scala/releases/tag/v2.11.11
Relative ticket - https://github.com/scala/scala-dev/issues/385

2.11.9 and 2.11.10 were withdrawn.

---

client/src/main/scala/com.olegych.scastie.client/components/editor/CodeReadOnly.scala

Changed read-only matching to not break after adding additional characters (at the end of comment)

Changed read-only matching to not break after adding additional characters

---

project/SbtShared.scala

This probably won't work out of the box due to the recent artefact naming conventions change. See https://contributors.scala-lang.org/t/dotty-artefacts-naming-change/4532

Upgrade Dotty to 3.0.0-M1

---

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala
api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala
client/src/main/scala/com.olegych.scastie.client/Routing.scala
client/src/main/scala/com.olegych.scastie.client/components/BuildSettings.scala
project/SbtShared.scala

The scastie version currently deployed allows the user to choose only 1 version for Scala 3 and it is not 3.0.0 but 3.0.1-RC1.
This PR introduces support for multiple Scala 3 versions in the user interface reusing the same strategy used for Scala 2

Support multiple Scala3 versions, including stable

---

client/src/main/resources/sass/dark.scss

#fff in dark mode blurs out the text "different configuration" making it unreadable except in light mode.
you can verify this by opening scastie --> change to dark mode and click "up" which is the last option at the bottom left of the screen.
Before
After

#fff in darkmode causes text to become unreadable

---

project/SbtShared.scala

I hope that is how "latest3" is intended to be used (i.e. for the current latest RC), it seems this is how it has been for 3.0.0 and 3.0.1-RC2 at least
closes #518

Add support for latest scala 3.0.2-RC1, closes #518

---

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala
client/src/main/scala/com.olegych.scastie.client/components/BuildSettings.scala
client/src/main/scala/com.olegych.scastie.client/components/ScaladexSearch.scala

Is this with https://github.com/scalacenter/scaladex/pull/687 enough to fix #514 ?
I am not sure about https://github.com/vincenzobaz/scastie/blob/8f11f31673a482c5c4d109c685c66e1811cf1d71/api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala#L269

Search artifacts for Scala 3 instead of always crossing 2.13

---

runtime-scala/src/main/scala/com.olegych.scastie.api.runtime/SharedRuntime.scala

This is a fix for https://github.com/scalacenter/scastie/issues/534.
I haven't written any test, because it looks like `SharedRuntime` isn't tested anywhere, so I assumed it was more of an "if it works empirically, that's good enough for us".
If the maintainers need tests, I'd be happy to add them but would require a little bit of help getting started with setting them up. I'm not at all familiar with the project's internal.

Make value rendering null-safe

---

.github/workflows/test.yml
CONTRIBUTING.md
default.nix
project/DockerHelper.scala
sbt-runner/src/main/scala/com.olegych.scastie.sbt/OutputExtractor.scala
utils/src/main/scala/com.olegych.scastie/util/BlockingProcess.scala

Things done:
- Update JDK packages in `CONTRIBUTING.md` installation instructions,
- use a recent snapshot of `nixos-unstable`,
- simplify `default.nix`,
- update runner base image and
- replace no longer supported use process PID via reflection with
the `.pid()` getter.
I tested this locally with `startAll` and by using the runner in the Docker container and it seems to work but I may well have missed something.

Run on Java 17

---

client/src/main/resources/prod.html

This PR adds statistics collection to Scastie using a self hosted Plausible instance.
[Plausible](https://plausible.io/) is open source and privacy-friendly tool. All the data is stored on the Scala Center' servers.

Add stats collection

---

api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala
project/SbtShared.scala

up to you if you want to merge it now (because 2.13.8 JARs are on Maven Central), or wait until the release is fully announced (hopefully Wednesday)

add Scala 2.13.8

---

.sbtopts

with this present, sbt won't start at all on my M1 Mac, regardless of whether I use JDK 8, 11, or 17
so whatever the disease was here, the cure seems to be worse

remove workaround which doesn't work on M1 Macs

---

build.sbt

This reverts previous vite migration changes of link output directory extraction made in last commit. They are breaking during packaging and pass while bundling production. It will fix the issue

revert changes to vite output directory extraction

---

package.json
vite.config.js

JVM is emmiting warning when it is run inside nix-shell
[0.005s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /tmp/nix-chroot.BeJFjH/sys/fs/cgroup/cpuset.
Adding `-J-Xlog:all=error` flag to the sbt process should suppress it and the deployment should be fixed.

Don't emit jvm warnings and infos for scalajs output directory extraction

---

client/src/main/resources/sass/tooltip.scss

Codemirror wraps lint hovers when pointing at underline into additional div with broke the css.

Fix css for lint messages

---

.scala-steward.conf

We don't want Scala version updates as in Scastie we are updating it manually.
Also Scalafmt changes do auto formating so they should be separated into separate PRs

Adjust scala steward updates

---

vite.config.js

Initially, with a clean build (using `sbt > startAll` and `yarn dev`), the proxy fails for API requests.
Tested on Linux 6.1.7-1-MANJARO.
Thanks to @rochala for the help!

Changed the proxy targets to 0.0.0.0

---

.scalafmt.conf

Currently this is throwing in error in our Scala Steward run at
https://github.com/scalacenter/steward/actions/runs/4169119430/jobs/7216704753#step:5:613 since
this is Scala 3 code that is currently being ran as with the scala2 dialect. This change just adds in an override for that dir to ensure it's treated as Scala 3

fix: add scalafmt fileoverride for runtime

---

client/src/main/resources/dev/embedded.js
client/src/main/resources/dev/main.js
client/src/main/resources/prod/embedded.js
client/src/main/resources/prod/main.js
package.json
vite.config.js
yarn.lock

~~CI ONLY Until vite-plugin-scalajs is actually published, we use a local copy of its source code.~~
~~At this point, this is only a proof-of-concept that we can actually, meaningfully use vite-plugin-scalajs in a larger project. It seems so. :)~~

Use vite-plugin-scalajs to link Vite and the Scala.js output.

---

sbt-runner/src/main/scala/com.olegych.scastie.sbt/OutputExtractor.scala

Fixes https://github.com/scalacenter/scastie/issues/865

separate all messages during reload

---

build.sbt

On windows, the yarn process needs to be launched with `yarn.bat`
Similar to https://github.com/scalameta/mdoc/pull/803

Correctly load yarn on Windows machines

---

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala

Noticed at https://contributors.scala-lang.org/t/add-warning-on-self-recursive-call-for-scala-3-like-scala-2-has/6599

update kind-projector for 2.13.13

---

api/src/main/scala/com.olegych.scastie.api/ScalaVersions.scala
project/SbtShared.scala

at https://contributors.scala-lang.org/t/scala-2-13-14-release-planning/6581/14 @sjrd said "I might not do earlier [Scala.js] releases" for 2.13.14, so I went ahead and bumped to 1.16.0 — let's see how CI likes it
review by @rochala ?

Scala 2.13.14, Scala.js 1.16.0

---

sbt-runner/src/test/scala/com.olegych.scastie.sbt/FormatActorTest.scala

Follow-on to #1114, missed since tests are generally failing.

FormatActorTest: fix using old method signature

---

api/src/main/scala/com.olegych.scastie.api/ScalaTarget.scala

This PR updates the default Scala 3 version to use `BuildInfo.stableNext`, ensuring that Scastie always uses the latest stable Scala 3 version by default.
* **Updated `Scala3.default`** - Changed version to `BuildInfo.stableNext`

update Scala 3 default version to stableNext

---

client/src/main/resources/sass/build-settings.scss
client/src/main/scala/com.olegych.scastie.client/components/BuildSettings.scala
client/src/main/scala/com.olegych.scastie.client/components/ScaladexSearch.scala

This pull request introduces a new "Toolkit" toggle feature in the Scaladex search component, along with corresponding UI and styling updates. The most important changes include adding a toggle switch for enabling/disabling the Toolkit dependency, implementing the necessary logic for handling the toggle state, and updating the styles to support the new UI elements.

feat: add Toolkit toggle switch to ScaladexSearch
